version: '3.7'

services:
  couchdb:
    image: couchdb:2
    container_name: cern_db
    ports:
      - 5984:5984
  
  server:
    image: node:8.12
    container_name: cern_server
    depends_on:
      - couchdb
    volumes:
      - ./server:/cern
    working_dir: /cern
    ports:
      - 3000:3000
    command: npm start
